spring.application.name=gateway
spring.output.ansi.enabled=always
spring.profiles.active=dev

# Prefix mới cho WebFlux Gateway
spring.cloud.gateway.server.webflux.routes[0].id=test
spring.cloud.gateway.server.webflux.routes[0].uri=https://httpbin.org
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/test/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/test/(?<segment>.*), /\${segment}

logging.level.org.springframework.cloud.gateway=DEBUG